### ISSUE TITLE
High-level estimate for integrating with MS Access database

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptor#1]
## Background
Aga Khan Foundation's Tajikistan office is using Microsoft Access to capture data collected across 30+ grants. We know very little and do not have access to the DB, but we know it's hosted locally and they're willing to provide us with direct access as needed. They want to integrate this DB with Salesforce Amp Impact to automate reporting for their grants on key indicators. 

## Request
Given what we know, can we determine a high-level estimate for integrating with MS Access? Do we need to build a language-pack? We can make a lot of assumptions, but I want to share a estimate with them to see if they're interested in moving forward with this project.

**Comment by aleksa-krolls** [comment]
cc @ritazagoni We might need to build a language-package for this one... so the team is looking into it to feed back into our high-level estimate for Amanda and Sharof.

**Comment by taylordowns2000** [comment]
@lakhassane , I'm thinking that this https://www.npmjs.com/package/node-adodb is a good place to start looking.

**Comment by taylordowns2000** [comment]
Hey @aleksa-krolls , @ritazagoni , I've done some research on how folks work with MS Access. In order to provide them with an estimate we'll need:

1. Connection credentials for a test db with the exact same configuration as their prod db (or limited access to the prod db)
2. Detailed instructions on how they connect to this Access Database from the _internet_ (i.e., not from windows applications running on their LAN, but from the web... outside their network)
3. A green light on ~4 hours of work

With that, we can probably figure out how long the adaptor and integration will take. Also note that even if they've never connected to the DB from outside their local network, it looks like we could implement or build an extension to their Access DB that would allow us to connect to it from the web, given that we had the support of their local IT team and there were no non-technical barriers to working with them, making modifications to their network, etc. (Though, if that's the case, we're likely talking small-software-project-scale rather than openfn-scale estimates.)

Hope this is a helpful start!

**Comment by aleksa-krolls** [comment]
@taylordowns2000 We cannot get access any time soon. So I need a high-level estimate... I will say we need these things to 100% confirm, but I need a sense of whether this is 2 days, 5 days, 10 days, etc.

**Comment by taylordowns2000** [comment]
Closing for now with details on Slack: https://openfn.slack.com/archives/G2LJCFFDW/p1605254029001100
